name: flutter_sheet_localization_test
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_sheet_localization: ^1.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_sheet_localization_generator: ^1.0.0
  build_runner: ^1.3.1

flutter:
  uses-material-design: true